export default [
  { value: 1, provincia: 16, label: 'Araba/Álava' },
  { value: 2, provincia: 8, label: 'Albacete' },
  { value: 3, provincia: 10, label: 'Alicante/Alacant' },
  { value: 4, provincia: 1, label: 'Almería' },
  { value: 5, provincia: 7, label: 'Ávila' },
  { value: 6, provincia: 11, label: 'Badajoz' },
  { value: 7, provincia: 4, label: 'Balears, Illes' },
  { value: 8, provincia: 9, label: 'Barcelona' },
  { value: 9, provincia: 7, label: 'Burgos' },
  { value: 10, provincia: 11, label: 'Cáceres' },
  { value: 11, provincia: 1, label: 'Cádiz' },
  { value: 12, provincia: 10, label: 'Castellón/Castelló' },
  { value: 13, provincia: 8, label: 'Ciudad Real' },
  { value: 14, provincia: 1, label: 'Córdoba' },
  { value: 15, provincia: 12, label: 'Coruña, A' },
  { value: 16, provincia: 8, label: 'Cuenca' },
  { value: 17, provincia: 9, label: 'Girona' },
  { value: 18, provincia: 1, label: 'Granada' },
  { value: 19, provincia: 1, label: 'Guadalajara' },
  { value: 20, provincia: 16, label: 'Gipuzkoa' },
  { value: 21, provincia: 1, label: 'Huelva' },
  { value: 22, provincia: 2, label: 'Huesca' },
  { value: 23, provincia: 1, label: 'Jaén' },
  { value: 24, provincia: 7, label: 'León' },
  { value: 25, provincia: 9, label: 'Lleida' },
  { value: 26, provincia: 17, label: 'Rioja, La' },
  { value: 27, provincia: 12, label: 'Lugo' },
  { value: 28, provincia: 13, label: 'Madrid' },
  { value: 29, provincia: 1, label: 'Málaga' },
  { value: 30, provincia: 14, label: 'Murcia' },
  { value: 31, provincia: 15, label: 'Navarra' },
  { value: 32, provincia: 12, label: 'Ourense' },
  { value: 33, provincia: 3, label: 'Asturias' },
  { value: 34, provincia: 7, label: 'Palencia' },
  { value: 35, provincia: 5, label: 'Palmas, Las' },
  { value: 36, provincia: 12, label: 'Pontevedra' },
  { value: 37, provincia: 7, label: 'Salamanca' },
  { value: 38, provincia: 5, label: 'Santa Cruz de Tenerife' },
  { value: 39, provincia: 6, label: 'Cantabria' },
  { value: 40, provincia: 7, label: 'Segovia' },
  { value: 41, provincia: 1, label: 'Sevilla' },
  { value: 42, provincia: 7, label: 'Soria' },
  { value: 43, provincia: 9, label: 'Tarragona' },
  { value: 44, provincia: 2, label: 'Teruel' },
  { value: 45, provincia: 8, label: 'Toledo' },
  { value: 46, provincia: 10, label: 'Valencia/València' },
  { value: 47, provincia: 7, label: 'Valladolid' },
  { value: 48, provincia: 16, label: 'Bizkaia' },
  { value: 49, provincia: 7, label: 'Zamora' },
  { value: 50, provincia: 2, label: 'Zaragoza' },
  { value: 51, provincia: 18, label: 'Ceuta' },
  { value: 52, provincia: 19, label: 'Melilla' }
];
